### ISSUE TITLE
MK1 S49 support ?

### ISSUE THREAD

**Issue by fury91** [ojacques/SynthesiaKontrol#11]
Hello, I don't know if I do something wrong, but I have some difficulties to make my MK1 S49 Working with the light guide.. I do not see the S49 between the choice when I launch SynthesiaKontrol.exe :(

I am on windows 10, with LoopBe1 installed

**Comment by ojacques** [comment]
MK1 S49 has been added to release 1.1. Is this the release you use? https://github.com/ojacques/SynthesiaKontrol/releases/tag/v1.1

**Comment by sixk32** [comment]
@ojacques -Thank you for your work on this, its very handy!

However, the 1.1 release only shows the 4 options. To get it to work I needed to run via Python after editting the offset to -36 for the S49 (mk1).

**Comment by LocoPlaya** [comment]
Folks, excuse my question... Could you please confirm if the support for Kontrol S49 MKI is included in the V1.1 or do I need to go through the extra steps described above? 

Many thanks in advance. And kudos to you ojacques for a this fantastic idea/creation!

**Comment by ojacques** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/339664db-f1f2-4375-b470-8d5151384691-7c004006-0295-48e1-9653-7cba73126934-v1.png?transparent=1&palette=1&width=246)

S49 MK1 is there on the master branch but not updated as a release. Can you check 1.2? https://github.com/ojacques/SynthesiaKontrol/releases/tag/v1.2

In any case,  @sixk32 - can you confirm that offset for S49 MK1 is -36 instead of -21 as [in the code right now?](https://github.com/ojacques/SynthesiaKontrol/blob/master/SynthesiaKontrol.py#L213)

**Comment by naenni** [comment]
Hey ojacques,
the right offset for the S49 MK1 is indeed -36!

**Comment by LeoDixon** [comment]
Hi! I got it to work on S49, somewhat. The offset is wrong, it should be -36. I changed it and now it shows on the right key. But It's only green lights. I don't know what's wrong, I'm not that skilled in python. I just found the offset thing by pure luck, trial and error.

**Comment by ojacques** [comment]
A fix has been released in [1.3](https://github.com/ojacques/SynthesiaKontrol/releases/tag/v1.3), with the help of @BrockAtkinson.
