### ISSUE TITLE
Komplete Kontrol S88 MK2 Lights showing up wrong

### ISSUE THREAD

**Issue by zeronimau5** [ojacques/SynthesiaKontrol#15]
Hello, i cannot seem to get the script working with the S88 MK2 
I have synthesia set to ch1 output on LoopBe port and the script running successfully 
however when i press the  middle c key the light for A1 shows up,
A3 lights up F#2. etc etc none of the keys light up as they should.
I have selected S88 MK2 in the script.
Is it a bug in the script or a user error on my end?.
Running Python3 with the dependencies on Mac OSX High Sierra

**Comment by amatacchieri** [comment]
Same problem here!!! Thanks for your time coding !!! :D

**Comment by amatacchieri** [comment]
I maybe found a workaround, I don't really still understand the logic of the code, I didn't had time to study it, so I don't actually garantee for this fix, but I found the following patch in the SynthesiaKontrol.py address the issue:

    elif keyboard == "2":
        MODE = "MK2"
        INSTR_ADDR = 0x1630 # KK S88 MK2
        NB_KEYS = 88
        OFFSET = -36

    elif keyboard == "2":
        MODE = "MK2"
        INSTR_ADDR = 0x1630 # KK S88 MK2
        NB_KEYS = 88
        OFFSET = -21

Now the script works perfectly. @ojacques, tell me if you need any help on that, I can contribute if you need.

Thanks for your effort coding it, it works really nice

**Comment by dcandela25** [comment]
Hey guys, 
I'm also having this issue. I've copied the source code and made the change from -36 to -21, but when I try to run this code I receive the following error:

c:\PythonPrograms>python SynthesiaKontrol.py
Traceback (most recent call last):
  File "SynthesiaKontrol.py", line 8, in <module>
    import hid
  File "C:\Python\lib\site-packages\hid\__init__.py", line 30, in <module>
    raise ImportError(error)
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll

Is there any advice for fixing these errors?

Thank you!

**Comment by lryjnks** [comment]
@amatacchieri are you using mac or windows?

how can i edit this without compiling?

**Comment by Downtime1989** [comment]
@amatacchieri would you mind talking me through step by step how to actually "patch" this completely new to all this and im really looking forward to having the light guide display the correct colours also 

thank you

**Comment by crotschcowski** [comment]
I have the same issue with S88MK2, lights shifted 15 semitones down. 

I edited the code and followed the readme instructions and installed python3 and libraries, but when i attempt to run the program 

python3 SynthesiaKontrol.py


Nothing happens, no error or anything. I dont get a cmd window popup asking me for my device like when i run the executable. 

Does anyone have any ideas what could be going wrong? Or better yet since this seems to be a frequent problem does anyone have an updated executable with the -21 offset? 

Thanks!

**Comment by crotschcowski** [comment]
I have the same issue with S88MK2, lights shifted 15 semitones down. 

I edited the code and followed the readme instructions and installed python3 and libraries, but when i attempt to run the program 

python3 SynthesiaKontrol.py


Nothing happens, no error or anything. I dont get a cmd window popup asking me for my device like when i run the executable. 

Does anyone have any ideas what could be going wrong? Or better yet since this seems to be a frequent problem does anyone have an updated executable with the -21 offset? 

Thanks so much for help!

**Comment by lryjnks** [comment]
Hey @crotschcowski ,

maybe try to run your CMD as Administrator. 
If this still doenst work, i should have a compiled fixed version on my pc :)

**Comment by crotschcowski** [comment]
@lryjnks thanks that did it! Working perfectly. Thanks to all for this amazing work!!!

**Comment by lryjnks** [comment]
> @lryjnks thanks that did it! Working perfectly. Thanks to all for this amazing work!!!

Glad to hear that! 👍

**Comment by ojacques** [comment]
Thanks everyone and @amatacchieri for identifying the correct offset. I did release [v1.3](https://github.com/ojacques/SynthesiaKontrol/releases/tag/v1.3) which has this change embedded.
